// ─── Global Alliance Atlas Hub Database & Geocoding Engine ───────────────────
import { EGYPT_CITIES } from './egyptCities';

export const GLOBAL_REGIONS = [
  { id: 'all', name: 'All Regions & Global', icon: '🌐' },
  { id: 'egypt', name: 'Egypt Ecosystem', icon: '🇪🇬' },
  { id: 'middle_east', name: 'Middle East & GCC', icon: '🇦🇪' },
  { id: 'europe', name: 'Europe & UK', icon: '🇬🇧' },
  { id: 'americas', name: 'Americas', icon: '🌎' },
  { id: 'asia', name: 'Asia & Africa', icon: '🌏' },
];

export const INTERNATIONAL_HUBS = [
  // ── United Kingdom & Europe ───────────────────────────────────────────────
  {
    id: 'manchester',
    name: 'Manchester',
    nameAr: 'مانشستر',
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    regionId: 'europe',
    regionName: 'Europe & UK',
    lat: 53.4808,
    lng: -2.2426,
    aliases: ['manchester', 'salford', 'greater manchester', 'مانشستر'],
  },
  {
    id: 'london',
    name: 'London',
    nameAr: 'لندن',
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    regionId: 'europe',
    regionName: 'Europe & UK',
    lat: 51.5074,
    lng: -0.1278,
    aliases: [
      'london',
      'greater london',
      'لندن',
      'uk',
      'united kingdom',
      'england',
      'بريطانيا',
      'انجلترا',
    ],
  },
  {
    id: 'birmingham',
    name: 'Birmingham',
    nameAr: 'برمنغهام',
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    regionId: 'europe',
    regionName: 'Europe & UK',
    lat: 52.4862,
    lng: -1.8904,
    aliases: ['birmingham', 'west midlands', 'برمنجهام', 'برمنغهام'],
  },
  {
    id: 'edinburgh',
    name: 'Edinburgh',
    nameAr: 'إدنبرة',
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    regionId: 'europe',
    regionName: 'Europe & UK',
    lat: 55.9533,
    lng: -3.1883,
    aliases: ['edinburgh', 'scotland', 'إدنبرة', 'ادنبرة'],
  },
  {
    id: 'berlin',
    name: 'Berlin',
    nameAr: 'برلين',
    country: 'Germany',
    countryCode: 'DE',
    flag: '🇩🇪',
    regionId: 'europe',
    regionName: 'Europe & UK',
    lat: 52.52,
    lng: 13.405,
    aliases: ['berlin', 'germany', 'deutschland', 'برلين', 'المانيا', 'ألمانيا'],
  },
  {
    id: 'munich',
    name: 'Munich',
    nameAr: 'ميونخ',
    country: 'Germany',
    countryCode: 'DE',
    flag: '🇩🇪',
    regionId: 'europe',
    regionName: 'Europe & UK',
    lat: 48.1351,
    lng: 11.582,
    aliases: ['munich', 'münchen', 'bayern', 'bavaria', 'ميونخ'],
  },
  {
    id: 'paris',
    name: 'Paris',
    nameAr: 'باريس',
    country: 'France',
    countryCode: 'FR',
    flag: '🇫🇷',
    regionId: 'europe',
    regionName: 'Europe & UK',
    lat: 48.8566,
    lng: 2.3522,
    aliases: ['paris', 'france', 'باريس', 'فرنسا'],
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    nameAr: 'أمستردام',
    country: 'Netherlands',
    countryCode: 'NL',
    flag: '🇳🇱',
    regionId: 'europe',
    regionName: 'Europe & UK',
    lat: 52.3676,
    lng: 4.9041,
    aliases: ['amsterdam', 'netherlands', 'holland', 'امستردام', 'أمستردام', 'هولندا'],
  },
  {
    id: 'dublin',
    name: 'Dublin',
    nameAr: 'دبلن',
    country: 'Ireland',
    countryCode: 'IE',
    flag: '🇮🇪',
    regionId: 'europe',
    regionName: 'Europe & UK',
    lat: 53.3498,
    lng: -6.2603,
    aliases: ['dublin', 'ireland', 'دبلن', 'أيرلندا', 'ايرلندا'],
  },
  {
    id: 'madrid',
    name: 'Madrid',
    nameAr: 'مدريد',
    country: 'Spain',
    countryCode: 'ES',
    flag: '🇪🇸',
    regionId: 'europe',
    regionName: 'Europe & UK',
    lat: 40.4168,
    lng: -3.7038,
    aliases: ['madrid', 'spain', 'مدريد', 'اسبانيا', 'إسبانيا'],
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    nameAr: 'برشلونة',
    country: 'Spain',
    countryCode: 'ES',
    flag: '🇪🇸',
    regionId: 'europe',
    regionName: 'Europe & UK',
    lat: 41.3879,
    lng: 2.1699,
    aliases: ['barcelona', 'catalonia', 'برشلونة'],
  },
  {
    id: 'rome',
    name: 'Rome',
    nameAr: 'روما',
    country: 'Italy',
    countryCode: 'IT',
    flag: '🇮🇹',
    regionId: 'europe',
    regionName: 'Europe & UK',
    lat: 41.9028,
    lng: 12.4964,
    aliases: ['rome', 'roma', 'italy', 'italia', 'روما', 'ايطاليا', 'إيطاليا'],
  },

  // ── Middle East & GCC ─────────────────────────────────────────────────────
  {
    id: 'dubai',
    name: 'Dubai',
    nameAr: 'دبي',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    flag: '🇦🇪',
    regionId: 'middle_east',
    regionName: 'Middle East & GCC',
    lat: 25.2048,
    lng: 55.2708,
    aliases: ['dubai', 'uae', 'united arab emirates', 'دبي', 'الإمارات', 'الامارات'],
  },
  {
    id: 'abu_dhabi',
    name: 'Abu Dhabi',
    nameAr: 'أبو ظبي',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    flag: '🇦🇪',
    regionId: 'middle_east',
    regionName: 'Middle East & GCC',
    lat: 24.4539,
    lng: 54.3773,
    aliases: ['abu dhabi', 'abudhabi', 'أبو ظبي', 'ابو ظبي', 'أبوظبي'],
  },
  {
    id: 'riyadh',
    name: 'Riyadh',
    nameAr: 'الرياض',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    flag: '🇸🇦',
    regionId: 'middle_east',
    regionName: 'Middle East & GCC',
    lat: 24.7136,
    lng: 46.6753,
    aliases: [
      'riyadh',
      'saudi',
      'saudi arabia',
      'ksa',
      'الرياض',
      'السعودية',
      'المملكة العربية السعودية',
    ],
  },
  {
    id: 'jeddah',
    name: 'Jeddah',
    nameAr: 'جدة',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    flag: '🇸🇦',
    regionId: 'middle_east',
    regionName: 'Middle East & GCC',
    lat: 21.5433,
    lng: 39.1728,
    aliases: ['jeddah', 'jidda', 'جدة', 'جده', 'مكة'],
  },
  {
    id: 'doha',
    name: 'Doha',
    nameAr: 'الدوحة',
    country: 'Qatar',
    countryCode: 'QA',
    flag: '🇶🇦',
    regionId: 'middle_east',
    regionName: 'Middle East & GCC',
    lat: 25.2854,
    lng: 51.531,
    aliases: ['doha', 'qatar', 'الدوحة', 'قطر'],
  },
  {
    id: 'kuwait_city',
    name: 'Kuwait City',
    nameAr: 'الكويت',
    country: 'Kuwait',
    countryCode: 'KW',
    flag: '🇰🇼',
    regionId: 'middle_east',
    regionName: 'Middle East & GCC',
    lat: 29.3759,
    lng: 47.9774,
    aliases: ['kuwait', 'kuwait city', 'الكويت', 'مدينة الكويت'],
  },
  {
    id: 'manama',
    name: 'Manama',
    nameAr: 'المنامة',
    country: 'Bahrain',
    countryCode: 'BH',
    flag: '🇧🇭',
    regionId: 'middle_east',
    regionName: 'Middle East & GCC',
    lat: 26.2285,
    lng: 50.586,
    aliases: ['manama', 'bahrain', 'المنامة', 'البحرين'],
  },
  {
    id: 'muscat',
    name: 'Muscat',
    nameAr: 'مسقط',
    country: 'Oman',
    countryCode: 'OM',
    flag: '🇴🇲',
    regionId: 'middle_east',
    regionName: 'Middle East & GCC',
    lat: 23.588,
    lng: 58.3829,
    aliases: ['muscat', 'oman', 'مسقط', 'عمان', 'سلطنة عمان'],
  },
  {
    id: 'amman',
    name: 'Amman',
    nameAr: 'عمان',
    country: 'Jordan',
    countryCode: 'JO',
    flag: '🇯🇴',
    regionId: 'middle_east',
    regionName: 'Middle East & GCC',
    lat: 31.9454,
    lng: 35.9284,
    aliases: ['amman', 'jordan', 'عمان', 'الأردن', 'الاردن'],
  },
  {
    id: 'beirut',
    name: 'Beirut',
    nameAr: 'بيروت',
    country: 'Lebanon',
    countryCode: 'LB',
    flag: '🇱🇧',
    regionId: 'middle_east',
    regionName: 'Middle East & GCC',
    lat: 33.8938,
    lng: 35.5018,
    aliases: ['beirut', 'lebanon', 'بيروت', 'لبنان'],
  },
  {
    id: 'casablanca',
    name: 'Casablanca',
    nameAr: 'الدار البيضاء',
    country: 'Morocco',
    countryCode: 'MA',
    flag: '🇲🇦',
    regionId: 'middle_east',
    regionName: 'Middle East & GCC',
    lat: 33.5731,
    lng: -7.5898,
    aliases: ['casablanca', 'rabat', 'morocco', 'الدار البيضاء', 'المغرب', 'الرباط', 'مراكش'],
  },
  {
    id: 'istanbul',
    name: 'Istanbul',
    nameAr: 'إسطنبول',
    country: 'Turkey',
    countryCode: 'TR',
    flag: '🇹🇷',
    regionId: 'middle_east',
    regionName: 'Middle East & GCC',
    lat: 41.0082,
    lng: 28.9784,
    aliases: ['istanbul', 'turkey', 'türkiye', 'اسطنبول', 'إسطنبول', 'تركيا'],
  },

  // ── Americas ──────────────────────────────────────────────────────────────
  {
    id: 'sao_paulo',
    name: 'São Paulo',
    nameAr: 'ساو باولو',
    country: 'Brazil',
    countryCode: 'BR',
    flag: '🇧🇷',
    regionId: 'americas',
    regionName: 'Americas',
    lat: -23.5505,
    lng: -46.6333,
    aliases: ['são paulo', 'sao paulo', 'brazil', 'brasil', 'ساو باولو', 'البرازيل'],
  },
  {
    id: 'rio_de_janeiro',
    name: 'Rio de Janeiro',
    nameAr: 'ريو دي جانيرو',
    country: 'Brazil',
    countryCode: 'BR',
    flag: '🇧🇷',
    regionId: 'americas',
    regionName: 'Americas',
    lat: -22.9068,
    lng: -43.1729,
    aliases: ['rio de janeiro', 'rio', 'ريو دي جانيرو'],
  },
  {
    id: 'buenos_aires',
    name: 'Buenos Aires',
    nameAr: 'بوينس آيرس',
    country: 'Argentina',
    countryCode: 'AR',
    flag: '🇦🇷',
    regionId: 'americas',
    regionName: 'Americas',
    lat: -34.6037,
    lng: -58.3816,
    aliases: ['buenos aires', 'argentina', 'بوينس آيرس', 'الأرجنتين', 'الارجنتين'],
  },
  {
    id: 'new_york',
    name: 'New York',
    nameAr: 'نيويورك',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    regionId: 'americas',
    regionName: 'Americas',
    lat: 40.7128,
    lng: -74.006,
    aliases: [
      'new york',
      'nyc',
      'ny',
      'brooklyn',
      'manhattan',
      'usa',
      'united states',
      'نيويورك',
      'أمريكا',
      'امريكا',
    ],
  },
  {
    id: 'san_francisco',
    name: 'San Francisco',
    nameAr: 'سان فرانسيسكو',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    regionId: 'americas',
    regionName: 'Americas',
    lat: 37.7749,
    lng: -122.4194,
    aliases: [
      'san francisco',
      'sf',
      'silicon valley',
      'bay area',
      'palo alto',
      'california',
      'سان فرانسيسكو',
      'كاليفورنيا',
    ],
  },
  {
    id: 'los_angeles',
    name: 'Los Angeles',
    nameAr: 'لوس أنجلوس',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    regionId: 'americas',
    regionName: 'Americas',
    lat: 34.0522,
    lng: -118.2437,
    aliases: ['los angeles', 'la', 'لوس أنجلوس', 'لوس انجلوس'],
  },
  {
    id: 'boston',
    name: 'Boston',
    nameAr: 'بوسطن',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    regionId: 'americas',
    regionName: 'Americas',
    lat: 42.3601,
    lng: -71.0589,
    aliases: ['boston', 'cambridge ma', 'massachusetts', 'بوسطن'],
  },
  {
    id: 'austin',
    name: 'Austin',
    nameAr: 'أوستن',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    regionId: 'americas',
    regionName: 'Americas',
    lat: 30.2672,
    lng: -97.7431,
    aliases: ['austin', 'texas', 'tx', 'أوستن', 'اوستن', 'تكساس'],
  },
  {
    id: 'toronto',
    name: 'Toronto',
    nameAr: 'تورونتو',
    country: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    regionId: 'americas',
    regionName: 'Americas',
    lat: 43.6532,
    lng: -79.3832,
    aliases: ['toronto', 'canada', 'ontario', 'تورونتو', 'كندا'],
  },
  {
    id: 'vancouver',
    name: 'Vancouver',
    nameAr: 'فانكوفر',
    country: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    regionId: 'americas',
    regionName: 'Americas',
    lat: 49.2827,
    lng: -123.1207,
    aliases: ['vancouver', 'british columbia', 'فانكوفر'],
  },

  // ── Asia & Africa ─────────────────────────────────────────────────────────
  {
    id: 'mumbai',
    name: 'Mumbai',
    nameAr: 'مومباي',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    regionId: 'asia',
    regionName: 'Asia & Africa',
    lat: 19.076,
    lng: 72.8777,
    aliases: ['mumbai', 'bombay', 'india', 'مومباي', 'الهند'],
  },
  {
    id: 'delhi',
    name: 'Delhi',
    nameAr: 'دلهي',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    regionId: 'asia',
    regionName: 'Asia & Africa',
    lat: 28.6139,
    lng: 77.209,
    aliases: ['delhi', 'new delhi', 'ncr', 'دلهي', 'نيودلهي'],
  },
  {
    id: 'bengaluru',
    name: 'Bengaluru',
    nameAr: 'بنغالور',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    regionId: 'asia',
    regionName: 'Asia & Africa',
    lat: 12.9716,
    lng: 77.5946,
    aliases: ['bengaluru', 'bangalore', 'karnataka', 'بنغالور'],
  },
  {
    id: 'singapore',
    name: 'Singapore',
    nameAr: 'سنغافورة',
    country: 'Singapore',
    countryCode: 'SG',
    flag: '🇸🇬',
    regionId: 'asia',
    regionName: 'Asia & Africa',
    lat: 1.3521,
    lng: 103.8198,
    aliases: ['singapore', 'سنغافورة'],
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    nameAr: 'طوكيو',
    country: 'Japan',
    countryCode: 'JP',
    flag: '🇯🇵',
    regionId: 'asia',
    regionName: 'Asia & Africa',
    lat: 35.6762,
    lng: 139.6503,
    aliases: ['tokyo', 'japan', 'طوكيو', 'اليابان'],
  },
  {
    id: 'sydney',
    name: 'Sydney',
    nameAr: 'سيدني',
    country: 'Australia',
    countryCode: 'AU',
    flag: '🇦🇺',
    regionId: 'asia',
    regionName: 'Asia & Africa',
    lat: -33.8688,
    lng: 151.2093,
    aliases: ['sydney', 'australia', 'nsw', 'سيدني', 'استراليا', 'أستراليا'],
  },
  {
    id: 'nairobi',
    name: 'Nairobi',
    nameAr: 'نيروبي',
    country: 'Kenya',
    countryCode: 'KE',
    flag: '🇰🇪',
    regionId: 'asia',
    regionName: 'Asia & Africa',
    lat: -1.2921,
    lng: 36.8219,
    aliases: ['nairobi', 'kenya', 'نيروبي', 'كينيا'],
  },
  {
    id: 'lagos',
    name: 'Lagos',
    nameAr: 'لاغوس',
    country: 'Nigeria',
    countryCode: 'NG',
    flag: '🇳🇬',
    regionId: 'asia',
    regionName: 'Asia & Africa',
    lat: 6.5244,
    lng: 3.3792,
    aliases: ['lagos', 'nigeria', 'لاغوس', 'نيجيريا'],
  },
];

// Convert Egypt cities to Global Hub format
export const EGYPT_GLOBAL_HUBS = EGYPT_CITIES.map((c) => ({
  ...c,
  country: 'Egypt',
  countryCode: 'EG',
  flag: '🇪🇬',
  regionId: 'egypt',
  regionName: 'Egypt Ecosystem',
}));

// All combined hubs worldwide
export const ALL_WORLD_HUBS = [...EGYPT_GLOBAL_HUBS, ...INTERNATIONAL_HUBS];

/**
 * Resolves any member's location (object or string) into a structured hub with coordinates.
 * Always guarantees valid latitude and longitude.
 */
export function resolveMemberLocation(location) {
  if (!location) {
    return {
      hubId: 'cairo',
      hubName: 'Cairo & Giza',
      country: 'Egypt',
      flag: '🇪🇬',
      regionId: 'egypt',
      regionName: 'Egypt Ecosystem',
      lat: 30.0444,
      lng: 31.2357,
      isResolved: false,
    };
  }

  let cityStr = '';
  let countryStr = '';
  let combined = '';

  if (typeof location === 'string') {
    combined = location.toLowerCase().trim();
    cityStr = combined;
  } else if (typeof location === 'object') {
    cityStr = (location.city || '').toLowerCase().trim();
    countryStr = (location.country || '').toLowerCase().trim();
    const district = (location.district || '').toLowerCase().trim();
    const state = (location.state || '').toLowerCase().trim();
    combined = `${cityStr} ${district} ${state} ${countryStr}`.trim();
  }

  // 1. Try matching with international hubs
  for (const hub of INTERNATIONAL_HUBS) {
    for (const alias of hub.aliases) {
      if (combined.includes(alias) || cityStr === alias || countryStr === alias) {
        return {
          hubId: hub.id,
          hubName: hub.name,
          country: hub.country,
          flag: hub.flag,
          regionId: hub.regionId,
          regionName: hub.regionName,
          lat: hub.lat,
          lng: hub.lng,
          isResolved: true,
        };
      }
    }
  }

  // 2. Try matching with Egypt cities
  for (const hub of EGYPT_GLOBAL_HUBS) {
    for (const alias of hub.aliases) {
      if (combined.includes(alias) || cityStr === alias) {
        return {
          hubId: hub.id,
          hubName: hub.name,
          country: 'Egypt',
          flag: '🇪🇬',
          regionId: 'egypt',
          regionName: 'Egypt Ecosystem',
          lat: hub.lat,
          lng: hub.lng,
          isResolved: true,
        };
      }
    }
  }

  // 3. Fallback for Egypt mentions or default
  if (
    !countryStr ||
    countryStr === 'egypt' ||
    countryStr === 'مصر' ||
    combined.includes('egypt') ||
    combined.includes('مصر')
  ) {
    return {
      hubId: 'cairo',
      hubName: 'Cairo & Giza',
      country: 'Egypt',
      flag: '🇪🇬',
      regionId: 'egypt',
      regionName: 'Egypt Ecosystem',
      lat: 30.0444,
      lng: 31.2357,
      isResolved: true,
    };
  }

  // 4. Default global fallback
  return {
    hubId: 'cairo',
    hubName: cityStr || 'Cairo & Giza',
    country: countryStr || 'Egypt',
    flag: '🌍',
    regionId: 'egypt',
    regionName: 'Global',
    lat: 30.0444,
    lng: 31.2357,
    isResolved: false,
  };
}
